### PR TITLE
DAT-22 Add option to set Authorization header forwarding in routes

### PR DESCRIPTION
**Pull request by rcrichton**

### CODE REVIEW

**Comment by hnnesv** [comment]
Tested and it works well! I just found it a bit confusing having this and the username/password fields on the route panel, i.e. it isn't really clear from a UI pov what happens if you set it to true and have other basic auth details for the route (i saw of course when running a transaction that the auth forwarding takes precedence over the route's basic auth details).

How about we just disable the username/password fields if forward is set to true? that way it's immediately clear to the user that auth forwarding will take place, regardless of what value is set for username/password?

**Comment by hnnesv** [comment]
Another super-minor point - maybe set forward auth to false for a new channel? rather then unselected?

**Comment by rcrichton** [comment]
@hnnesv ok cool, I'l work on those.

**Comment by rcrichton** [comment]
@hnnesv please review again.

**Comment by hnnesv** [comment]
👍

**Pull request merged**
