### PR TITLE
OHM-316 delete visualizer

### PR DESCRIPTION
**Pull request by rcrichton**

### CODE REVIEW

**Comment by hnnesv** [comment]
@rcrichton it doesn't seem to work for me when I try to delete the last visualizer in the list. I don't think it's a core issue as the endpoint isn't called. Any ideas? Does this scenario work for you?
(my core's on latest master atm)

**Comment by hnnesv** [comment]
@rcrichton it's looking good - just the last visualizer issue above

**Comment by rcrichton** [comment]
@hnnesv ready for re-review

**Comment by hnnesv** [comment]
👍 Looks good!

**Pull request merged**
