### PR TITLE
Tasks pagination

### PR DESCRIPTION
**Pull request by BMartinos**
This PR relates to issue: https://github.com/jembi/openhim-console/issues/255 and fixed issue: https://github.com/jembi/openhim-console/issues/254

### CODE REVIEW

**Comment by BMartinos** [comment]
Hey @devcritter Do you mind reviewing this PR for me when you get a chance. Thanks. This PR work along side the tasks-pagination branch in core

**Comment by devcritter** [comment]
:+1: Thanks @BMartinos it works really well!

**Comment by BMartinos** [comment]
Hey @devcritter . Sorry ive added a few small changes to the Tasks Filtering while working with it. Mind just having a quick look

**Comment by devcritter** [comment]
:+1:

**Pull request merged**
