### PR TITLE
Channel load fix

### PR DESCRIPTION
**Pull request by BMartinos**
Fixed an issue with channel load results including an extra day. Had to do date validation to only add if timestamp falls within past 7 days (current day included)

### CODE REVIEW

**Comment by BMartinos** [comment]
Hey @rcrichton do you mind just reviewing this fix for me quick. Thanks

**Comment by rcrichton** [comment]
We have decided to hold off on this and hide the channel load column as we can't figure out the deferences yet.

**Comment by rcrichton** [comment]
@BMartinos I think we should close this PR now. Its been too long and I don't think we actually need to put effort into fixing this. What do you think?

**Comment by BMartinos** [comment]
@rcrichton sure that's fine with me. We can re-open the issue again if it becomes problematic but id say close it for now

**Pull request closed without merging**
