### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by BMartinos**
This PR relates to issue: https://github.com/jembi/openhim-console/issues/207

All tests still passing. I did not notice any broken code or functions due to the updates. All still seems to be functioning as excpected.

### CODE REVIEW

**Comment by BMartinos** [comment]
Hey @devcritter Do you mind just reviewing this PR for me. Ive stared looking at updating the bower packages but there are quite a few things that break on the console. Mainly UI functionality which would need to be updated at multiple places

**Comment by devcritter** [comment]
Thanks @BMartinos Have you checked that bower.json is up to date? If not we should update those dependencies as well.

**Comment by BMartinos** [comment]
Update issues: 

Updating angular to version 1.4.0 had some major breaking changes (This includes the sub-modules like angular-cookies, angular-resources, angular-routes etc)

bootstrap -> 3.3.4: Styling issues - also broke the datepicker date range. Duplicated the input field into the other one ( date range always the same )
bootstrap-datepicker -> 1.4.0: Styling issues

**Comment by BMartinos** [comment]
Hey @devcritter Mind looking of the this PR when you get a chance. There are some dependencies i couldnt update as it had major and minor breaking changes. Thanks

**Comment by devcritter** [comment]
:+1: Looks good. Would you mind just creating tickets for each of those breaking changes? Thanks

**Pull request merged**
